#!/bin/sh
# Behavioral coverage for compile-spell:
# - shows usage with --help
# - shows usage with -h
# - requires spell name argument
# - fails for unknown spell

# Locate the repository root so we can source test-bootstrap
# Start from this test's directory and walk upward until spells/.imps/test/test-bootstrap is found
# shellcheck disable=SC2034
# (SC2034: test_root is used by sourced helpers)
test_root=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)
while [ ! -f "$test_root/spells/.imps/test/test-bootstrap" ] && [ "$test_root" != "/" ]; do
  test_root=$(dirname "$test_root")
done
. "$test_root/spells/.imps/test/test-bootstrap"

test_compile_spell_help() {
  _run_spell spells/spellcraft/compile-spell --help
  _assert_success
  _assert_output_contains "Usage: compile-spell"
}

test_compile_spell_help_h_flag() {
  _run_spell spells/spellcraft/compile-spell -h
  _assert_success
  _assert_output_contains "Usage: compile-spell"
}

test_compile_spell_requires_args() {
  _run_spell spells/spellcraft/compile-spell
  _assert_failure
  _assert_error_contains "spell name required"
}

test_compile_spell_unknown_spell() {
  _run_spell spells/spellcraft/compile-spell nonexistent_spell_xyz
  _assert_failure
  _assert_error_contains "not found"
}

test_compile_spell_produces_valid_script() {
  # Test that compile-spell produces a valid shell script
  _run_spell spells/spellcraft/compile-spell hash
  _assert_success
  _assert_output_contains "#!/bin/sh"
  _assert_output_contains "# Compiled from: hash"
  _assert_output_contains "# Generated by compile-spell"
}

test_compile_spell_output_is_executable() {
  # Test that compiled output can be executed
  tmpdir=$(_make_tempdir)
  tmpfile="$tmpdir/hash-compiled"
  _run_spell spells/spellcraft/compile-spell hash > "$tmpfile"
  chmod +x "$tmpfile"
  
  # Run the compiled spell's --help
  if "$tmpfile" --help >/dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

_run_test_case "compile-spell shows help" test_compile_spell_help
_run_test_case "compile-spell shows help with -h" test_compile_spell_help_h_flag
_run_test_case "compile-spell requires arguments" test_compile_spell_requires_args
_run_test_case "compile-spell fails for unknown spell" test_compile_spell_unknown_spell
_run_test_case "compile-spell produces valid script" test_compile_spell_produces_valid_script
_run_test_case "compile-spell output is executable" test_compile_spell_output_is_executable

_finish_tests
