#!/bin/sh
# is-integer VALUE - test if value is a valid integer (positive, negative, or zero)
# Example: is-integer "42" && echo "valid"


case "$1" in
  '') return 1 ;;
  -) return 1 ;;
  -[0-9]) : ;;
  -[0-9]*) : ;;
  [0-9]*) : ;;
  *) return 1 ;;
esac
case "$1" in
  -*) _ii_rest=${1#-}; case "$_ii_rest" in *[!0-9]*) return 1 ;; esac ;;
  *[!0-9]*) return 1 ;;
esac
return 0

