#!/bin/sh

# This script is a magical tome of sorcery, commanding the elusive entity known as Tor.

case "${1-}" in
  -h|--help)
    printf 'Usage: tor-menu\n'
    printf 'Displays the Tor management menu.\n'
    exit 0
    ;;
esac

set -eu
. colors

# Catch Ctrl-C and TERM signal to exit cleanly
trap 'exit 0' INT TERM

# Displays the menu
display_menu() {
  title="${BOLD}${CYAN}TOR: $(tor-status)"
  set_config="Configure Tor%configure-tor"
  repair_permissions="Repair Permissions%sudo repair-tor-permissions"
  exit_label=$(exit-label)
  exit_option="${exit_label}%kill -TERM \$PPID"
  
  if is-installed tor > /dev/null; then
    install_tor_option="Uninstall Tor%uninstall-tor"
    if sudo tor-bridge-status; then
    	bridge_option="Disable Bridge Mode%sudo configure-tor-bridge"
    else
        bridge_option="Enable Bridge Mode%sudo configure-tor-bridge"
    fi
    if is-service-installed tor > /dev/null; then
    	install_service_option="Uninstall Tor Service%remove-service tor"
    	service_status_option="View Tor Service Status%sudo systemctl status tor"
	    if is-service-running tor > /dev/null; then
	      tor_service_option="Stop Tor Service%sudo systemctl stop tor"
	      menu "$title" "$set_config" "$repair_permissions" "$bridge_option" "$service_status_option" "$tor_service_option" "$install_service_option" "$install_tor_option" "$exit_option"
	    else
	      tor_service_option="Start Tor Service%sudo systemctl start tor"
	      menu "$title" "$set_config" "$repair_permissions" "$bridge_option" "$service_status_option" "$tor_service_option" "$install_service_option" "$install_tor_option" "$exit_option"
	    fi
    else
    	script_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    	install_service_option="Install Tor Service%install-service-template $script_dir/tor.service \"TORPATH=\`which tor\`\" \"TORRCPATH=/etc/tor/torrc\""
    	menu "$title" "$set_config" "$repair_permissions" "$bridge_option" "$install_service_option" "$install_tor_option" "$exit_option"
	fi
  else
    install_tor_option="Install Tor%install-tor"
    menu "$title" "$install_tor_option" "$exit_option"
  fi
}

first_run=1

# Main execution loop
while true; do
  if [ "$first_run" -eq 0 ]; then
    printf '\n'
  else
    first_run=0
  fi

  display_menu || true
done
