#!/bin/sh
# assert-output-contains SUBSTRING - test that OUTPUT contains substring
# Testing imp - fails if OUTPUT variable doesn't contain the substring
# Example: assert-output-contains "hello"

_test_assert_output_contains() {
  _taoc_substring=$1
  case "${OUTPUT-}" in
    *"$_taoc_substring"*)
      return 0
      ;;
    *)
      TEST_FAILURE_REASON="output missing substring: $_taoc_substring"
      return 1
      ;;
  esac
}
