#!/bin/sh
# assert-output-contains SUBSTRING - test that OUTPUT contains substring
# Testing imp - fails if OUTPUT variable doesn't contain the substring
# Example: assert-output-contains "hello"

substring=$1
case "${OUTPUT-}" in
  *"$substring"*)
    exit 0
    ;;
  *)
    TEST_FAILURE_REASON="output missing substring: $substring"
    exit 1
    ;;
esac
