#!/bin/sh
# clear-traps - clear all signal traps
# Example: clear-traps

set -eu

_clear_traps() {
  trap - EXIT HUP INT TERM
}

# Self-execute when run directly (not sourced)
case "$0" in
  */clear-traps) [ "${_WIZARDRY_SOURCING:-}" != "1" ] && _clear_traps "$@" ;; esac
