#!/bin/sh
# on-exit COMMAND [ARGS...] - register cleanup command to run on exit/interrupt
# Example: on-exit cleanup-file "$tmpfile"

set -eu

on_exit() {
  trap "$*" EXIT HUP INT TERM
}

# Self-execute when run directly (not sourced)
case "$0" in
  */on-exit) on_exit "$@" ;; esac
