#!/bin/sh
# trim - remove leading/trailing whitespace from stdin
# Example: echo "  hello  " | trim

set -eu

_trim() {
  sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

# Self-execute when run directly (not sourced)
case "$0" in
  */trim) _trim "$@" ;; esac
