#!/bin/sh
# from CMD CMD_ARGS SOURCE MORE... - prepend SOURCE to command args
# Receives: $1=command, $2=command_args, $3=source, $4+=remaining
# Example: parse cp to /tmp from /etc/hosts


from_cmd=${1:-}
from_cmd_args=${2:-}
shift 2 2>/dev/null || shift $#

if [ $# -lt 1 ]; then
  printf '%s: from requires a source\n' "from" >&2
  exit 1
fi

from_source=$1
shift

if [ -z "$from_cmd" ]; then
  printf '%s: from requires a command before it\n' "from" >&2
  exit 1
fi

if [ $# -eq 0 ]; then
  from_had_noglob=0
  case $- in
    *f*) from_had_noglob=1 ;;
    *) set -f ;;
  esac
  if [ -n "$from_cmd_args" ]; then
    # shellcheck disable=SC2086
    "$from_cmd" "$from_source" $from_cmd_args
    from_status=$?
  else
    "$from_cmd" "$from_source"
    from_status=$?
  fi
  if [ "$from_had_noglob" -eq 0 ]; then
    set +f
  fi
  exit "$from_status"
fi

from_lex_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)
from_had_noglob=0
case $- in
  *f*) from_had_noglob=1 ;;
  *) set -f ;;
esac
# shellcheck disable=SC2086
set -- "$from_cmd" "$from_source" $from_cmd_args "$@"
if [ "$from_had_noglob" -eq 0 ]; then
  set +f
fi
. "$from_lex_dir/parse"
exit $?
