#!/bin/sh
# from CMD CMD_ARGS SOURCE MORE... - prepend SOURCE to command args
# Receives: $1=command, $2=command_args, $3=source, $4+=remaining
# Example: parse cp to /tmp from /etc/hosts


from_cmd=${1:-}
from_cmd_args=${2:-}
shift 2 2>/dev/null || shift $#

if [ $# -lt 1 ]; then
  printf '%s: from requires a source\n' "from" >&2
  exit 1
fi

from_source=$1
shift

if [ -z "$from_cmd" ]; then
  printf '%s: from requires a command before it\n' "from" >&2
  exit 1
fi

if [ -n "$from_cmd_args" ]; then
  from_new_args="$from_source $from_cmd_args"
else
  from_new_args=$from_source
fi

if [ $# -eq 0 ]; then
  # shellcheck disable=SC2086
  "$from_cmd" $from_new_args
  exit $?
fi

from_lex_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)
# shellcheck disable=SC2086
"$from_lex_dir/parse" "$from_cmd" $from_new_args "$@"

