#!/bin/sh
# into CMD CMD_ARGS TARGET MORE... - append TARGET to command args
# Receives: $1=command, $2=command_args, $3=target, $4+=remaining
# Example: parse cp file.txt into /tmp


into_cmd=${1:-}
into_cmd_args=${2:-}
shift 2 2>/dev/null || shift $#

if [ $# -lt 1 ]; then
  printf '%s: into requires a target\n' "into" >&2
  exit 1
fi

into_target=$1
shift

if [ -z "$into_cmd" ]; then
  printf '%s: into requires a command before it\n' "into" >&2
  exit 1
fi

if [ $# -eq 0 ]; then
  into_had_noglob=0
  case $- in
    *f*) into_had_noglob=1 ;;
    *) set -f ;;
  esac
  if [ -n "$into_cmd_args" ]; then
    # shellcheck disable=SC2086
    "$into_cmd" $into_cmd_args "$into_target"
    into_status=$?
  else
    "$into_cmd" "$into_target"
    into_status=$?
  fi
  if [ "$into_had_noglob" -eq 0 ]; then
    set +f
  fi
  exit "$into_status"
fi

into_lex_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)
into_had_noglob=0
case $- in
  *f*) into_had_noglob=1 ;;
  *) set -f ;;
esac
# shellcheck disable=SC2086
set -- "$into_cmd" $into_cmd_args "$into_target" "$@"
if [ "$into_had_noglob" -eq 0 ]; then
  set +f
fi
. "$into_lex_dir/parse"
exit $?
