#!/bin/sh
# each COMMAND [ARGS...] - run command for each line of stdin
# Line appended as last arg. Example: ls | each echo "File:"
set -eu


while IFS= read -r _each_line; do "$@" "$_each_line"; done
