#!/bin/sh
# last [FILE] - output only the last line of input or file
# Example: tail_entry=$(last log.txt)
set -eu

last() {

  if [ "$#" -ge 1 ]; then tail -n 1 "$1"; else tail -n 1; fi
}

last "$@"
