#!/bin/sh
# take N [FILE] - take first N lines of input or file
# Example: take 5 file.txt   # first 5 lines
set -eu

take() {

  if [ "$#" -ge 2 ]; then head -n "$1" "$2"; else head -n "$1"; fi
}

# Self-execute when run directly (not sourced)
case "$0" in
  */take) take "$@" ;; esac