#!/bin/sh
# ensure-parent-dir FILE - create parent directory of file if it doesn't exist
# Example: ensure-parent-dir "$HOME/.config/app/config.txt"

set -eu


epd_file=${1-}
epd_dir=epd_file%/*}

if [ "$epd_dir" != "$epd_file" ] && [ ! -d "$epd_dir" ]; then
  mkdir -p "$epd_dir"
fi
