#!/bin/sh
# is-posint VALUE - test if VALUE is a positive integer (greater than 0)
# Example: is-posint "$count" && echo "valid count"


case "$1" in
  ''|*[!0-9]*) exit 1 ;;
  0) exit 1 ;;
  *) exit 0 ;;
esac

