#!/bin/sh
# no VALUE - test if value is negative (n/no/false/0/N/NO/FALSE)
# Example: no "$VERBOSE" && echo "quiet mode"

_no() {
  case "$1" in
    n|N|no|NO|No|false|FALSE|False|0) return 0 ;;
    *) return 1 ;;
  esac
}
