#!/bin/sh
# nonempty VALUE - test if string is non-empty (has content)
# Example: nonempty "$NAME" && echo "Hello, $NAME"

# Note: No set -eu because this is a conditional imp (returns exit codes for flow control)


[ -n "$1" ]

