#!/bin/sh
# Usage: get-priority [CRC32 hash]
# Outputs the priority for the given card hash (in the curent directory)

FILE_HASH="${1}"

# Search for the file using the hash and get its priority
find . -type f -exec read-magic '{}' hash \; | grep "${FILE_HASH}" | awk '{print $1}' | xargs read-magic priority