#!/bin/sh

# This script gets the new priority for a given file.
# Usage: get-new-priority [FILE]

FILE="${1}"

# Hash the file
hashchant "${FILE}" > /dev/null
file_hash=$(read-magic "${FILE}" hash)

# Get the directory of the file
DIR="$(dirname "${FILE}")"

# Start with a highest priority of 0
highest_priority=0

# Loop through all files in the directory
for f in "${DIR}"/*; do
  # Get the file's priority
  file_priority=$(read-magic "${f}" priority 2>/dev/null)

  # Check if the priority is a number
  if [ "${file_priority}" -eq "${file_priority}" ] 2>/dev/null; then
    # If the file's priority is higher than the current highest priority, update highest_priority
    [ "${file_priority}" -gt "${highest_priority}" ] && highest_priority="${file_priority}"
  fi
done

# Get the current priorities of the directory
dir_priorities=$(read-magic "${DIR}" priorities)

# If there's no other file in the directory, the new priority is 1
if [ -z "${dir_priorities}" ]; then
  echo "1"
  exit 0
fi

# Check if the file is in the highest echelon
echo "${dir_priorities}" | tr ',' '\n' | while read -r priority_hash; do
  # Get the priority file
  priority_file=$(get-card "${priority_hash}")

  # Get priority of the file
  file_priority=$(read-magic "${priority_file}" priority)

  # Check if the priority is a number
  if [ "${file_priority}" -eq "${file_priority}" ] 2>/dev/null; then
    # If the current file's priority is not the highest priority, 
    # the new priority is the same as the highest priority
    if [ "${file_priority}" -ne "${highest_priority}" ]; then
      echo "${highest_priority}"
      exit 0
    fi
  fi
done

# If the file is in the highest echelon, its new priority is one higher than the highest priority
echo "$((highest_priority + 1))"