#!/bin/sh
# record-failure-detail IDX - add a test index to the list of failures
# Appends the index to _fail_detail_indices for summary output.
set -eu

idx=$1

_fail_detail_indices=$(printf '%s\n%s\n' "$_fail_detail_indices" "$idx" |
  awk 'NF { if (!seen[$0]++) { order[++count]=$0 } }
       END { for (i=1; i<=count; i++) { if (i>1) printf(","); printf order[i] } }')


