#!/bin/sh
# stub-ask-text DIR RESPONSE - create ask-text stub with fixed response
set -eu

dir=$1
response=$2
cat >"$dir/ask-text" <<EOF_INNER
#!/bin/sh
echo "$response"
EOF_INNER
chmod +x "$dir/ask-text"
