#!/bin/sh
# newer FILE1 FILE2 - test if FILE1 is newer than FILE2
# Example: newer src.c src.o && compile src.c

_newer() {
  [ "$1" -nt "$2" ]
}

# Self-execute when run directly (not sourced)
case "$0" in
  */newer) _newer "$@" ;; esac
